#%RAML 1.0 Trait

description: client id enforcements traits
headers:
  client_id:
    type: string
    minLength: 16
    maxLength: 32
  client_secret: 
    type: string
    minLength: 16
    maxLength: 32

